name: Build Employee App
on: [push]

jobs:
  build:
    runs-on:ubutu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Docker Image
        uses: docker build -t emp_mngmt_app .
    